SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Models/ViewModels/MatchViewModel.cs
namespace SportSystem.Web.Models
{
    using System;

    using SportSystem.Common.Mappings;
    using SportSystem.Models;

    public class MatchViewModel : IMapFrom<Match>
    {
        public int Id { get; set; }

        public int HomeTeamId { get; set; }

        public virtual Team HomeTeam { get; set; }

        public int AwayTeamId { get; set; }

        public virtual Team AwayTeam { get; set; }

        public DateTime MatchDate { get; set; }
    }
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Controllers/CommentsController.cs
namespace SportSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNet.Identity;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using System.Web.Mvc;
    using SportSystem.Web.Models;
    using SportSystem.Common.SystemMessages;
    using System.Net;
    using SportSystem.Data.UnitOfWork;
    using SportSystem.Models;

    [Authorize]
    public class CommentsController : BaseController
    {
        public CommentsController(ISportSystemData data)
            : base(data)
        {
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CommentInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                model.AuthorId = this.UserProfile.Id;
                var comment = Mapper.Map<Comment>(model);

                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var createdComment = this.Data.Comments
                                         .All()
                                         .Where(c => c.Id == comment.Id)
                                         .Project()
                                         .To<CommentViewModel>()
                                         .FirstOrDefault();

                this.AddSystemMessage(string.Format("Comment from {0} added.", createdComment.Author), SystemMessageType.Success);
                return this.PartialView("DisplayTemplates/CommentViewModel", createdComment);
            }

            this.AddSystemMessage("Cannot add comment!", SystemMessageType.Error);
            return this.Json(this.ModelState);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var comment = this.Data.Comments.All().FirstOrDefault(c => c.Id == id);
            if (comment != null && this.User.Identity.GetUserId() == comment.AuthorId)
            {
                this.Data.Comments.Delete(comment);
                this.Data.SaveChanges();

                this.AddSystemMessage(string.Format("Comment {0} was deleted.", comment.Id), SystemMessageType.Success);
                return this.Content(string.Empty);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Cannot delete comment!");
        }
	}
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Controllers/MatchesController.cs
namespace SportSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    using System.Web.Mvc;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using System.Web.Mvc.Expressions;
    using PagedList;
    using SportSystem.Common;
    using SportSystem.Common.SystemMessages;
    using SportSystem.Data.UnitOfWork;
    using SportSystem.Models;
    using SportSystem.Web.Models;

    [Authorize]
    public class MatchesController : BaseController
    {
        public MatchesController(ISportSystemData data)
            :base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var matches = this.Data.Matches
                             .All()
                             .OrderBy(m => m.MatchDate)
                             .ThenBy(m => m.Id)
                             .Project()
                             .To<MatchViewModel>()
                             .ToPagedList(page ?? GlobalConstants.DefaultPageNumber, GlobalConstants.DefaultPageSize);

            return this.View(matches);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(x => x.Index(GlobalConstants.DefaultPageNumber));
            }

            var matches = this.Data
                              .Matches
                              .All()
                              .Include(x => x.Comments)
                              .FirstOrDefault(b => b.Id == id);

            var teamsModel = Mapper.Map<MatchDetailViewModel>(matches);

            return this.View(teamsModel);
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            this.LoadTeams();
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MatchInputModel model)
        {
            if (model.AwayTeamId == null || model.HomeTeamId == null || 
                model.HomeTeamId == model.AwayTeamId)
            {
                this.AddSystemMessage(string.Format("Please select teams from drop menu"), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());   
            }

            var existingMatch = this.Data.Matches.All().FirstOrDefault(m => m.HomeTeamId == model.HomeTeamId && 
                                                            m.AwayTeamId == model.AwayTeamId);
            if (existingMatch != null)
            {
                this.AddSystemMessage(string.Format("Match {0} - {1} allready exist!", existingMatch.HomeTeam.Name, existingMatch.AwayTeam.Name), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());
            }

            var homeTeam = this.Data.Teams.All().FirstOrDefault(t => t.Id == model.HomeTeamId);
            var awayTeam = this.Data.Teams.All().FirstOrDefault(t => t.Id == model.AwayTeamId);
            model.HomeTeam = homeTeam;
            model.AwayTeam = awayTeam;
            
            if (model != null && this.ModelState.IsValid)
            {
                var match = Mapper.Map<Match>(model);
                this.Data.Matches.Add(match);
                this.Data.SaveChanges();
                this.AddSystemMessage(string.Format("Match {0} - {1} added to DB.", match.HomeTeam.Name, match.AwayTeam.Name), SystemMessageType.Success);
                return this.RedirectToAction(x => x.Details(match.Id));
            }

            return this.RedirectToAction(x => x.Create());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Bet(int id, decimal? HomeBet, decimal? AwayBet)
        {
            var match = this.Data.Matches
                                 .All()
                                 .Include(x => x.Bets)
                                 .FirstOrDefault(b => b.Id == id);

            if (match != null)
            {
                this.Data.Bets
                         .Add(new Bet
                         {
                             HomeBet = HomeBet ?? 0,
                             AwayBet = AwayBet ?? 0,
                             MatchId = id,
                             UserId = this.UserProfile.Id
                         });

                this.Data.SaveChanges();

                var homeBets = match.Bets.Sum(v => v.HomeBet);
                var awayBets = match.Bets.Sum(v => v.AwayBet);

                if (HomeBet != null)
                {
                    return this.Content(homeBets.ToString());
                }

                return this.Content(awayBets.ToString());
            }

            return new EmptyResult();
        }

        private void LoadTeams()
        {
            this.ViewBag.Teams = this.Data
                                     .Teams
                                     .All()
                                     .Select(x => new SelectListItem
                                     {
                                         Value = x.Id.ToString(),
                                         Text = x.Name
                                     });
        }
	}
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Matches/Create.cshtml
@model SportSystem.Web.Models.MatchInputModel
@{
    ViewBag.Title = "Create Match";
}
@using (Html.BeginForm("Create", "Matches", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
     @Html.AntiForgeryToken()
     @Html.ValidationSummary(true)
    <h2 class="text-center">Create Matches</h2>
    <hr />
    <div id="teams-list">
        @Html.Partial("_ListTeamsPartial")
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.MatchDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">         
            @Html.EditorFor(m => m.MatchDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.MatchDate)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Matches/Details.cshtml
@model SportSystem.Web.Models.MatchDetailViewModel
@{
    ViewBag.Title = "Match Details";
}
<h2 class="text-center">Match details</h2>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <p>
                    <strong>Home Team: </strong>
                    <em>@Model.HomeTeam.Name</em>
                    <strong class="text-success">(Bets: $<span id="home-bet-count">@Model.Bets.Sum(b => b.HomeBet)</span>)</strong>
                </p>
                <p>
                    <strong>Away Team: </strong>
                    <em>@Model.AwayTeam.Name</em>
                    <strong class="text-success">(Bets: $<span id="away-bet-count">@Model.Bets.Sum(b => b.AwayBet)</span>)</strong>
                </p>
                <p>
                    <strong>Date: </strong>
                    <em>@Model.MatchDate</em>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h3 class="text-center">Bets:</h3>
        <div id="home-bet">
            @using (Ajax.BeginForm("Bet", "Matches", new { id = Model.Id }, new AjaxOptions()
                            {
                                HttpMethod = "POST",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "home-bet-count",
                                OnSuccess = "onBetSuccess"
                            }, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.HomeBet, new { @class = "col-md-3 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.HomeBet, new { @class = "form-control" })
                    </div>
                    <input type="submit" class="btn btn-sm btn-primary" value="Bet" />
                    <div class="col-md-12 pull-left"> 
                        @Html.ValidationMessageFor(m => m.HomeBet)
                    </div>
                </div>
            }
        </div>
        <div id="away-bet">
            @using (Ajax.BeginForm("Bet", "Matches", new { id = Model.Id }, new AjaxOptions()
                            {
                                HttpMethod = "POST",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "away-bet-count",
                                OnSuccess = "onBetSuccess"
                            }, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.AwayBet, new { @class = "col-md-3 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.AwayBet, new { @class = "form-control" })
                    </div>
                    <input type="submit" class="btn btn-sm btn-primary" value="Bet" />
                    <div class="col-md-12 pull-left"> 
                        @Html.ValidationMessageFor(m => m.AwayBet)
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="col-md-12" id="comments">
    <h3>Commnets:</h3>
    @if (Model.Comments.Any())
    {
        @Html.DisplayFor(m => m.Comments)
    }
    else
    {
        <p class="text-left text-danger" id="no-comments">No commnets!</p>
    }
</div>

<div class="col-md-12">
    @using (Ajax.BeginForm("Add", "Comments", new { MatchId = Model.Id }, new AjaxOptions()
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.InsertAfter,
            UpdateTargetId = "comments",
            OnSuccess = "emptyTextareaForm"
        }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <h4 class="text-center">Add comment</h4>
        <hr />
        <div class="form-group">
            @Html.Label("Comment text", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextArea("Content", "", 5, 150, new { @class = "form-control", id = "textarea" })
                @Html.ValidationMessage("Content")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" class="btn btn-default" value="Add Comment" />
            </div>
        </div>
    }
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryunobtrusive")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function emptyTextareaForm () {
            document.getElementById("textarea").value = '';
            document.getElementById("no-comments").value = '';
        }

        function onVoteSuccess() {
            var button = document.getElementById("vote-button");
            button.parentNode.removeChild(button);
        }

        function onBetSuccess() {
            document.getElementById("HomeBet").value = '';
            document.getElementById("AwayBet").value = '';
        }
    </script>
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Matches/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<SportSystem.Web.Models.MatchViewModel>
@{
    ViewBag.Title = "All Matches";
}
<h2 class="text-center">All Matches</h2>
<div class="row text-center">
    @Html.DisplayFor(m => m)
</div>

<div class="row text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>