SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Controllers/MatchesController.cs
namespace SportSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    using System.Web.Mvc;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using System.Web.Mvc.Expressions;
    using PagedList;
    using SportSystem.Common;
    using SportSystem.Common.SystemMessages;
    using SportSystem.Data.UnitOfWork;
    using SportSystem.Models;
    using SportSystem.Web.Models;

    [Authorize]
    public class MatchesController : BaseController
    {
        public MatchesController(ISportSystemData data)
            :base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var matches = this.Data.Matches
                             .All()
                             .OrderBy(m => m.MatchDate)
                             .ThenBy(m => m.Id)
                             .Project()
                             .To<MatchViewModel>()
                             .ToPagedList(page ?? GlobalConstants.DefaultPageNumber, GlobalConstants.DefaultPageSize);

            return this.View(matches);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(x => x.Index(GlobalConstants.DefaultPageNumber));
            }

            var matches = this.Data
                              .Matches
                              .All()
                              .Include(x => x.Comments)
                              .FirstOrDefault(b => b.Id == id);

            var teamsModel = Mapper.Map<MatchDetailViewModel>(matches);

            return this.View(teamsModel);
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            this.LoadTeams();
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MatchInputModel model)
        {
            if (model.AwayTeamId == null || model.HomeTeamId == null || 
                model.HomeTeamId == model.AwayTeamId)
            {
                this.AddSystemMessage(string.Format("Please select teams from drop menu"), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());   
            }

            var existingMatch = this.Data.Matches.All().FirstOrDefault(m => m.HomeTeamId == model.HomeTeamId && 
                                                            m.AwayTeamId == model.AwayTeamId);
            if (existingMatch != null)
            {
                this.AddSystemMessage(string.Format("Match {0} - {1} allready exist!", existingMatch.HomeTeam.Name, existingMatch.AwayTeam.Name), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());
            }

            var homeTeam = this.Data.Teams.All().FirstOrDefault(t => t.Id == model.HomeTeamId);
            var awayTeam = this.Data.Teams.All().FirstOrDefault(t => t.Id == model.AwayTeamId);
            model.HomeTeam = homeTeam;
            model.AwayTeam = awayTeam;
            
            if (model != null && this.ModelState.IsValid)
            {
                var match = Mapper.Map<Match>(model);
                this.Data.Matches.Add(match);
                this.Data.SaveChanges();
                this.AddSystemMessage(string.Format("Match {0} - {1} added to DB.", match.HomeTeam.Name, match.AwayTeam.Name), SystemMessageType.Success);
                return this.RedirectToAction(x => x.Details(match.Id));
            }

            return this.RedirectToAction(x => x.Create());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Bet(int id, decimal? HomeBet, decimal? AwayBet)
        {
            var match = this.Data.Matches
                                 .All()
                                 .Include(x => x.Bets)
                                 .FirstOrDefault(b => b.Id == id);

            if (match != null)
            {
                this.Data.Bets
                         .Add(new Bet
                         {
                             HomeBet = HomeBet ?? 0,
                             AwayBet = AwayBet ?? 0,
                             MatchId = id,
                             UserId = this.UserProfile.Id
                         });

                this.Data.SaveChanges();

                var homeBets = match.Bets.Sum(v => v.HomeBet);
                var awayBets = match.Bets.Sum(v => v.AwayBet);

                if (HomeBet != null)
                {
                    return this.Content(homeBets.ToString());
                }

                return this.Content(awayBets.ToString());
            }

            return new EmptyResult();
        }

        private void LoadTeams()
        {
            this.ViewBag.Teams = this.Data
                                     .Teams
                                     .All()
                                     .Select(x => new SelectListItem
                                     {
                                         Value = x.Id.ToString(),
                                         Text = x.Name
                                     });
        }
	}
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Controllers/PlayersController.cs
namespace SportSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Mvc.Expressions;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using PagedList;
    using SportSystem.Common;
    using SportSystem.Common.SystemMessages;
    using SportSystem.Data.UnitOfWork;
    using SportSystem.Models;
    using SportSystem.Web.Models;

    [Authorize]
    public class PlayersController : BaseController
    {
        public PlayersController(ISportSystemData data)
            :base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var players = this.Data
                              .Players
                              .All()
                              .OrderBy(p => p.Name)
                              .ThenBy(p => p.BirthDate)
                              .Project()
                              .To<PlayerViewModel>()
                              .ToPagedList(page ?? GlobalConstants.DefaultPageNumber, GlobalConstants.DefaultPageSize);

            return this.View(players);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(x => x.Index(GlobalConstants.DefaultPageNumber));
            }

            var player = this.Data
                             .Players
                             .All()
                             .FirstOrDefault(p => p.Id == id);

            var playerModel = Mapper.Map<PlayerDetailViewModel>(player);

            return this.View(playerModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlayerInputModel model)
        {
            var existPlayer = this.Data
                                  .Players
                                  .All()
                                  .Any(p => p.Name == model.Name);
            if (existPlayer)
            {
                this.AddSystemMessage(string.Format("Player {0} allready exist!", model.Name), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());
            }
            if (model != null && this.ModelState.IsValid)
            {
                var player = Mapper.Map<Player>(model);
                this.Data.Players.Add(player);
                this.Data.SaveChanges();
                this.AddSystemMessage(string.Format("Player {0} added to DB!", model.Name), SystemMessageType.Success);
                return this.RedirectToAction(x => x.Details(player.Id));
            }

            this.AddSystemMessage(string.Format("Somting go wrong!"), SystemMessageType.Warning);
            return this.RedirectToAction(x => x.Create());
        }
	}
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Controllers/TeamsController.cs
namespace SportSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using PagedList;
    using System.Web.Mvc.Expressions;

    using SportSystem.Data.UnitOfWork;
    using SportSystem.Models;
    using SportSystem.Web.Models;
    using SportSystem.Common;
    using SportSystem.Common.SystemMessages;

    [Authorize]
    public class TeamsController : BaseController
    {
        public TeamsController(ISportSystemData data)
            :base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var teams = this.Data.Teams
                                .All()
                                .OrderBy(b => b.Name)
                                .Project()
                                .To<TeamViewModel>()
                                .ToPagedList(page ?? GlobalConstants.DefaultPageNumber, GlobalConstants.DefaultPageSize);

            return this.View(teams);
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(x => x.Index(GlobalConstants.DefaultPageNumber));
            }

            var teams = this.Data.Teams
                               .All()
                               .Include(x => x.Votes)
                               .FirstOrDefault(b => b.Id == id);
            var teamsModel = Mapper.Map<TeamDetailViewModel>(teams);

            var userId = this.User.Identity.GetUserId();
            teamsModel.UserHasVote = teams.Votes.Any(x => x.UserId == userId);

            return this.View(teamsModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            this.LoadFreePlayers();
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TeamInputModel model)
        {
            var existingTeam = this.Data.Teams.All().FirstOrDefault(t => t.Name == model.Name);
            if (existingTeam != null)
            {
                this.AddSystemMessage(string.Format("Team {0} allready exist.", existingTeam.Name), SystemMessageType.Warning);
                return this.RedirectToAction(x => x.Create());
            }

            if (model != null && this.ModelState.IsValid)
            {
                var team = Mapper.Map<Team>(model);
                this.Data.Teams.Add(team);

                foreach (var playerId in model.PlayersId)
                {
                    if (playerId != 0)
                    {
                        var player = this.Data.Players.All().FirstOrDefault(x => x.Id == playerId);
                        player.Team = team;
                        this.AddSystemMessage(string.Format("Player {0} added to team {1}.", player.Name, team.Name), SystemMessageType.Information);
                    }
                }

                this.Data.SaveChanges();
                this.AddSystemMessage(string.Format("Team {0} added to DB.", team.Name), SystemMessageType.Success);

                return this.RedirectToAction(x => x.Details(team.Id));
            }

            this.LoadFreePlayers();
            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Vote(int id)
        {
            var team = this.Data.Teams
                               .All()
                               .FirstOrDefault(b => b.Id == id);

            if (team != null)
            {
                var userHasVote = team.Votes.Any(v => v.UserId == this.User.Identity.GetUserId());
                if (!userHasVote)
                {
                    this.Data.Votes.Add(new Vote
                    {
                        TeamId = team.Id,
                        UserId = this.User.Identity.GetUserId(),
                        Value = 1
                    });

                    this.Data.SaveChanges();
                }

                var votesCount = team.Votes.Sum(v => v.Value);
                return this.Content(votesCount.ToString());
            }

            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult GetPlayersList()
        {
            this.LoadFreePlayers();
            return this.PartialView("_ListPlayersPartial");
        }

        private void LoadFreePlayers()
        {
            this.ViewBag.Players = this.Data
                                       .Players
                                       .All()
                                       .Where(x => x.TeamId == null)
                                       .Select(x => new SelectListItem
                                       {
                                            Value = x.Id.ToString(),
                                            Text = x.Name
                                       });
        }
	}
}

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sport System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("styles", false)
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sport System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("All Matches", "Index", "Matches", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("All Players", "Index", "Players", new { area = "" }, null)</li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("All Teams", "Index", "Teams", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Create Team", "Create", "Teams", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Create Match", "Create", "Matches", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Create Player", "Create", "Players", new { area = "" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_SystemMessages")
        @RenderBody()
        <hr />

    </div>
    <div class="panel-footer">
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - SportSystem ASP.NET Application</p>
        </footer>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.error-messages').delay(2500).fadeOut();
        });
    </script>
</body>
</html>

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Shared/_ListPlayersPartial.cshtml
@using System.Collections.Generic

<div class="form-group">
    @Html.Label("Player", new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.DropDownList("PlayersId", (IEnumerable<SelectListItem>)this.ViewBag.Players, "--- select player ---", new { name = "PlayersId[]", @class = "form-control" })
        @Html.ValidationMessage("PlayersId", "Select player", new { @class = "text-danger" })
    </div>
</div>

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Shared/_ListTeamsPartial.cshtml
@using System.Collections.Generic

<div class="form-group">
    @Html.Label("Home Team", new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.DropDownList("HomeTeamId", (IEnumerable<SelectListItem>)this.ViewBag.Teams, "--- select team ---", new { name = "HomeTeamId", @class = "form-control" })
        @Html.ValidationMessage("HomeTeamId", "Please select a team", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.Label("Away Team", new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.DropDownList("AwayTeamId", (IEnumerable<SelectListItem>)this.ViewBag.Teams, "--- select team ---", new { name = "AwayTeamId", @class = "form-control" })
        @Html.ValidationMessage("AwayTeamId", "Pleace select a team", new { @class = "text-danger" })
    </div>
</div>

SportSystem-Web-Application-ASP.NET-MVC/SportSystem.Web/Views/Shared/_SystemMessages.cshtml
@using SportSystem.Common.SystemMessages

@{
    var systemMessages = (List<SystemMessage>)ViewBag.SystemMessages;
}

@if (ViewBag.SystemMessages != null && systemMessages.Any())
{
    <div class="error-messages inner">
        <div class="container">
            <div class="col-md-12">
                @foreach (var message in systemMessages)
                {
                    var messageClass = string.Empty;
                    switch (message.Type)
                    {
                        case SystemMessageType.Information:
                            messageClass = "alert alert-info";
                            break;
                        case SystemMessageType.Success:
                            messageClass = "alert alert-success";
                            break;
                        case SystemMessageType.Warning:
                            messageClass = "alert alert-warning";
                            break;
                        case SystemMessageType.Error:
                            messageClass = "alert alert-danger";
                            break;
                    }

                    @:<div class="@messageClass text-center"><strong>@Html.Raw(message.Content)</strong></div>
                }
            </div>
        </div>
    </div>
}-